import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Store from "./_providers/Store";
import ReactQueryClient from "./_providers/ReactQueryClient";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Task management app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <Store>
        <ReactQueryClient>
          <body className={inter.className}>{children}</body>
        </ReactQueryClient>
      </Store>

    </html>
  );
}
